version: "3.4"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16

services:
  ethforward.dnp.dappnode.eth:
    build: ./build
    image: ethforward.dnp.dappnode.eth:0.1.3
    container_name: DAppNodeCore-ethforward.dnp.dappnode.eth
    restart: always
    dns: 172.33.1.2
    networks:
      network:
        ipv4_address: 172.33.1.3